// These styles apply to every route in the application
import './globals.css'
import { robotoFonts } from './ui/fonts'
import Footer from './components/Footer'
 
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${robotoFonts.className} antialiased`}>
        {children}
        <Footer/>
      </body>
      
    </html>
  )
}