### Home
GET http://localhost:3001/



### Registrar un usuario.
POST http://localhost:3001/users
Content-Type: application/json

{
"firstName":"Ruben",
"lastName":"Guarda",
"email":"ruben.guarda@correo.com",
"password":"123456"   
}




#### Register: Crea el usuario y genera un token
POST http://localhost:3001/register
Content-Type: application/json

{
"firstName": "carlos",
  "lastName": "Andres",
  "email": "carlos.guarda23@correo.com",
  "password":"leandro123"
  
}

### Login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "carlos.guarda23@correo.com",
  "password":"leandro123"
}
